spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
    exchange: catalog_ms.product
    product-created-queue: queue.product_created
    product-created-rk: product.event.created
  datasource:
    url: ${IDS_DATASOURCE_URL}
    username: ${IDS_MYSQL_USERNAME}
    password: ${IDS_MYSQL_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 9090
