services:
  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - msnet

  db:
    image: mysql:8
    volumes:
      - "./.docker/db/data:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shop_db
    networks:
      - msnet

networks:
  msnet:
