services:
  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - msnet

  catalogmsdb:
    image: mysql:8
    volumes:
      - "./.docker/catalogms/data:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalog_db
    networks:
      - msnet

  ordermsdb:
    image: mysql:8
    volumes:
      - "./.docker/orderms/data:/var/lib/mysql"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_db
    networks:
      - msnet

networks:
  msnet:
